## roles/patching/tasks/reboot-server.yml
---
- name: Reboot Linux node {{ inventory_hostname }}
  become: yes
  shell: /sbin/shutdown -r +0
  async: 0
  poll: 0
  ignore_errors: true
  when: ansible_distribution != "Solaris"

- name: Reboot Solaris node {{ inventory_hostname }}
  become: yes
  shell: /usr/sbin/shutdown -i 6 -y
  async: 0
  poll: 0
  ignore_errors: true
  when: ansible_distribution == "Solaris"

- name: Wait for server reboot
  become: no
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300 delay=30
...
